# vi: set ft=yaml et ts=2 sw=2 sts=0:

version: '2'
services:
  base: &default
    build: .
    image: mapk0y/codenize-tools
    env_file: envfile
    working_dir: /working/
    volumes:
      - ./:/working:rw
  # Security Group
  sg:
    <<: *default
    command: sh -c "piculet -e -o /working/Groupfile --split && rm /working/Groupfile && ruby inject_definition.rb"
  # IAM
  iam:
    <<: *default
    command: miam -e -o /working/IAMfile
  # Elastic IP
  eip:
    <<: *default
    command: eipmap -e -o /working/EIPfile
  # Route53
  route53:
    <<: *default
    command: roadwork -e -o /working/Routefile
  # Elastic Load Balancer
  elb:
    <<: *default
    command: kelbim -e -o /working/ELBfile
  # VPC RouteTable
  vpc:
    <<: *default
    command: mappru -e -o /working/Routetable
  # CroudFront
  cf:
    <<: *default
    command: cfdef -e -o /working/CFfile
  # Shell for Debug
  shell:
    <<: *default
    command: sh
