# vi: set ft=yaml et ts=2 sw=2 sts=0:

version: '2'
services:
  base: &default
    build: .
    build: mapk0y/codenize-tools
    env_file: envfile
    working_dir: /working/
    volumes:
      - ./:/working:ro
  # Security Group
  sg-dryrun:
    <<: *default
    command: piculet -a --dry-run -f /working/Groupfile
  sg-apply:
    <<: *default
    command: piculet -a -f /working/Groupfile
  # IAM
  iam-dryrun:
    <<: *default
    command: miam -a --dry-run -f /working/IAMfile
  iam-apply:
    <<: *default
    command: miam -a -f /working/IAMfile
  # Elastic IP
  eip-dryrun:
    <<: *default
    command: eipmap -a --dry-run -f /working/EIPfile
  eip-apply:
    <<: *default
    command: eipmap -a -f /working/EIPfile
  # Route53
  route53-test:
    <<: *default
    command: roadwork -t -f /working/Routefile
  route53-dryrun:
    <<: *default
    command: roadwork -a --dry-run -f /working/Routefile
  route53-apply:
    <<: *default
    command: roadwork -a -f /working/Routefile
  # Elastic Load Balancer
  elb-test:
    <<: *default
    command: kelbim -t /working/ELBfile
  elb-dryrun:
    <<: *default
    command: kelbim -a --dry-run -f /working/ELBfile
  elb-apply:
    <<: *default
    command: kelbim -a -f /working/ELBfile
  # Shell for Debug
  shell:
    <<: *default
    command: sh
